In [4]:
from Update_Scores import Tournament

In [5]:
EC2024 = Tournament('EC')

team_table = EC2024.team_table.set_index('Team').sort_values(['PNT', 'GD'], ascending=False)

person_table = EC2024.team_table.drop(columns='Team').groupby('Who').sum().sort_values(['PNT', 'GD'], ascending=False)

In [6]:
df = EC2024.fixtures.drop(columns='Special')

df

,Date,KO,Home person,Home team,Home score,Away score,Away team,Away person,Round,Status
0,2024-06-14,19:00,Mary,Germany,5,1,Scotland,Brendan,Group stage,Finished
1,2024-06-15,13:00,Sam,Hungary,1,3,Switzerland,Hugo,Group stage,Finished
2,2024-06-15,16:00,Brendan,Spain,3,0,Croatia,Adrian,Group stage,Finished
3,2024-06-15,19:00,Isaac,Italy,2,1,Albania,Scott,Group stage,Finished
4,2024-06-16,13:00,Mary,Poland,1,2,Netherlands,Alex,Group stage,Finished
5,2024-06-16,16:00,Isaac,Slovenia,1,1,Denmark,Scott,Group stage,Finished
6,2024-06-16,19:00,Alex,Serbia,0,1,England,Hugo,Group stage,Finished
7,2024-06-17,13:00,Adrian,Romania,3,0,Ukraine,Brendan,Group stage,Finished
8,2024-06-17,16:00,Sam,Belgium,0,1,Slovakia,Hugo,Group stage,Finished
9,2024-06-17,19:00,Isaac,Austria,0,1,France,Adrian,Group stage,Finished
10,2024-06-18,16:00,Mary,Turkey,3,1,Georgia,Alex,Group stage,Finished
11,2024-06-18,19:00,Scott,Portugal,2,1,Czechia,Sam,Group stage,Finished
12,2024-06-19,13:00,Adrian,Croatia,2,2,Albania,Scott,Group stage,Finished
13,2024-06-19,16:00,Mary,Germany,2,0,Hungary,Sam,Group stage,Finished
14,2024-06-19,19:00,Brendan,Scotland,1,1,Switzerland,Hugo,Group stage,Finished
15,2024-06-20,13:00,Isaac,Slovenia,1,1,Serbia,Alex,Group stage,Finished
16,2024-06-20,16:00,Scott,Denmark,1,1,England,Hugo,Group stage,Finished
17,2024-06-20,19:00,Brendan,Spain,1,0,Italy,Isaac,Group stage,Finished
18,2024-06-21,13:00,Hugo,Slovakia,1,2,Ukraine,Brendan,Group stage,Finished
19,2024-06-21,16:00,Mary,Poland,1,3,Austria,Isaac,Group stage,Finished
20,2024-06-21,19:00,Alex,Netherlands,0,0,France,Adrian,Group stage,Finished
21,2024-06-22,13:00,Alex,Georgia,1,1,Czechia,Sam,Group stage,Finished
22,2024-06-22,16:00,Mary,Turkey,0,3,Portugal,Scott,Group stage,Finished
23,2024-06-22,19:00,Sam,Belgium,2,0,Romania,Adrian,Group stage,Finished
24,2024-06-23,19:00,Brendan,Scotland,0,1,Hungary,Sam,Group stage,Finished
25,2024-06-23,19:00,Hugo,Switzerland,1,1,Germany,Mary,Group stage,Finished
26,2024-06-24,19:00,Scott,Albania,0,1,Spain,Brendan,Group stage,Finished
27,2024-06-24,19:00,Adrian,Croatia,1,1,Italy,Isaac,Group stage,Finished
28,2024-06-25,16:00,Adrian,France,1,1,Poland,Mary,Group stage,Finished
29,2024-06-25,16:00,Alex,Netherlands,2,3,Austria,Isaac,Group stage,Finished
30,2024-06-25,19:00,Scott,Denmark,0,0,Serbia,Alex,Group stage,Finished
31,2024-06-25,19:00,Hugo,England,0,0,Slovenia,Isaac,Group stage,Finished
32,2024-06-26,16:00,Brendan,Ukraine,None,None,Belgium,Sam,Group stage,Future
33,2024-06-26,16:00,Hugo,Slovakia,None,None,Romania,Adrian,Group stage,Future
34,2024-06-26,19:00,Sam,Czechia,None,None,Turkey,Mary,Group stage,Future
35,2024-06-26,19:00,Alex,Georgia,None,None,Portugal,Scott,Group stage,Future
36,2024-06-29,16:00,Hugo,Switzerland,None,None,Italy,Isaac,Last 16,Future

In [7]:
team_table

            PL  W  D  L GD PNT      Who
Team
France       0  0  0  0  0   0   Adrian
Croatia      0  0  0  0  0   0   Adrian
Romania      0  0  0  0  0   0   Adrian
Netherlands  0  0  0  0  0   0     Alex
Serbia       0  0  0  0  0   0     Alex
Georgia      0  0  0  0  0   0     Alex
Spain        0  0  0  0  0   0  Brendan
Ukraine      0  0  0  0  0   0  Brendan
Scotland     0  0  0  0  0   0  Brendan
England      0  0  0  0  0   0     Hugo
Switzerland  0  0  0  0  0   0     Hugo
Slovakia     0  0  0  0  0   0     Hugo
Italy        0  0  0  0  0   0    Isaac
Austria      0  0  0  0  0   0    Isaac
Slovenia     0  0  0  0  0   0    Isaac
Germany      0  0  0  0  0   0     Mary
Poland       0  0  0  0  0   0     Mary
Turkey       0  0  0  0  0   0     Mary
Belgium      0  0  0  0  0   0      Sam
Hungary      0  0  0  0  0   0      Sam
Czechia      0  0  0  0  0   0      Sam
Portugal     0  0  0  0  0   0    Scott
Denmark      0  0  0  0  0   0    Scott
Albania      0  0  0  0  0   0    Scott

In [8]:
person_table

        PL  W  D  L GD PNT
Who
Adrian   0  0  0  0  0   0
Alex     0  0  0  0  0   0
Brendan  0  0  0  0  0   0
Hugo     0  0  0  0  0   0
Isaac    0  0  0  0  0   0
Mary     0  0  0  0  0   0
Sam      0  0  0  0  0   0
Scott    0  0  0  0  0   0

In [11]:
EC2024.fixtures.columns

Index(['Date', 'KO', 'Home person', 'Home team', 'Home score', 'Away score',
       'Away team', 'Away person', 'Round', 'Special', 'Status'],
      dtype='object')